server:
  port: 8081

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: "default"

topic:
  names:
    CANCEL: t.cancel
    PROCESS: t.process
    UPDATE: t.update