server:
  port: 8081

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: "default"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: "com.github.epay.domain.dto.request.PaymentRequest"
            type:
              mapping: "com.github.blog.controller.dto.request.PaymentRequest:com.github.epay.domain.dto.request.PaymentRequest"
            trusted:
              packages: "com.github.blog.controller.dto.request.PaymentRequest"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  names:
    PROCESS: t.process
    CANCEL: t.cancel
    UPDATE: t.update

starter-epay:
  name: epay comp.