spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server:
  port: 8081

service:
  blog:
    base:
      url: http://blog:8080
    endpoints:
      UPDATE_STATE: /orders/update-state